version: 2

project_name: linker-keeper

before:
  hooks:
    - go mod tidy

builds:
  - id: linker-keeper
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w
      - -X 'main.VERSION={{ .Tag }}'
    env:
      - CGO_ENABLED=0

archives:
  - formats: ["tar.gz"]
    files:
      - README.md
      - README_zhCN.md
      - LICENSE

release:
  draft: false
